### ISSUE TITLE
您好，何不提交APICloud官方审核呢？还是官方的SDK好用啊

### ISSUE THREAD

**Issue by sipo1209** [AgoraIO/APICloud-SDK#1]
您好，何不提交APICloud官方审核更新呢？还是官方的SDK好用啊！

请问咱们可以提供编译后的版本么？

**Comment by guohai** [comment]
有这个想法，但是但暂时还没有确切的计划什么时候上。有消息会在这里更新。

**Comment by sipo1209** [comment]
> 有这个想法，但是但暂时还没有确切的计划什么时候上。有消息会在这里更新。

您好。这个ios版本下载下来后没法直接编译，我添加了官方的2.4.1的framework，添加了libUZEngin.a后仍然无法直接编译, 提示_unzOpen未定义。请问咱们有没有可能提供一个直接可以编译的版本？

**Comment by sipo1209** [comment]
ios版本成功编译小贴士：
1）要增加CoreML.framework的 依赖包
2）如果出现_uzOpen错误，要增加libminizip.a的link库

**Comment by guohai** [comment]
已经在官方上线最新 2.9.1 RTC SDK 版本。
https://www.apicloud.com/mod_detail/93891
